name: Deploy to Vercel

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: 'vercel'
  cancel-in-progress: true

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Restore cache
        uses: useblacksmith/cache@v5
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm install --force

      - name: Install Vercel CLI
        run: npm install -g vercel@latest --force

      - name: Pull Vercel environment variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
